from model.competition import Competition


class ModelProviderCompetition(object):

    @staticmethod
    def get_standard_competition(name="standard competition"):
        obj = Competition(name, 3, 1, 0, False, 'generated by model factory')
        return obj
